### ISSUE TITLE
Source Data

### ISSUE THREAD

**Issue by bnapora** [ChristianMarzahl/EIPH_WSI#1]
Hi Christian,

This is awesome work.  Is it possible to get a link to the raw data?  (WSI's or patches)  My goal is to attempt to emulate the study you performed.  There are so many innovative techniques in your work and I'd like to understand them better.  

Hopefully this is a reasonable request for access to the data.

Brian Napora

**Comment by bnapora** [comment]
Christian...any chance you can share the raw the data?

**Comment by ChristianMarzahl** [comment]
Dear Bnapora,

please send a request as described in the publication:
https://www.nature.com/articles/s41598-020-65958-2

I will provide you afterwards with a link to download the slides and annotations. 


With kind regards,
Christian Marzahl
